version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongodb_data:/data/db # Persistent storage for MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Admin username
      MONGO_INITDB_ROOT_PASSWORD: Changemeplz2079 # Admin password

  mongodb-compass:
    image: ghcr.io/mongodb-js/compass:latest
    container_name: mongodb_compass
    restart: always
    ports:
      - "9090:8080" # Access Compass through your browser (if supported by this image)
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Changemeplz2079

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8181:8081" # Access the web UI at http://<server-ip>:8181
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Changemeplz2079
      ME_CONFIG_MONGODB_SERVER: mongodb

  admin-mongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    restart: always
    ports:
      - "1234:1234" # Access the web UI at http://<server-ip>:1234
    environment:
      CONN_NAME: LocalMongo
      CONN_HOST: mongodb
      CONN_PORT: 27017
      CONN_USER: root
      CONN_PASS: Changemeplz2079

volumes:
  mongodb_data:
    driver: local
