bleach = [
    {
        "id": 1,
        "name": "⚡️ Юки",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/1.jpg",
    },
    {
        "id": 2,
        "name": "⚡️ Инаба",
        "rarity": "Обычная",
        "attack": 2000,
        "health": 3000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/2.jpg",
    },
    {
        "id": 3,
        "name": "⚡️ Ханакари",
        "rarity": "Обычная",
        "attack": 2000,
        "health": 2000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/3.jpg",
    },
    {
        "id": 4,
        "name": "⚡️ Тесла",
        "rarity": "Обычная",
        "attack": 2000,
        "health": 3000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/4.jpg",
    },
    {
        "id": 5,
        "name": "⚡️ Момо Хинамори",
        "rarity": "Обычная",
        "attack": 2000,
        "health": 3000,
        "value": 1000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/5.jpg",
    },
    {
        "id": 6,
        "name": "⚡️ Уруру Цумугия",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/6.jpg",
    },
    {
        "id": 7,
        "name": "⚡️ Хидетомо",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/7.jpg",
    },
    {
        "id": 8,
        "name": "⚡️ Кон",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 1000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/8.jpg",
    },
    {
        "id": 9,
        "name": "⚡️ Ханатаро Ямада",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 1000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/9.jpg",
    },
    {
        "id": 10,
        "name": "⚡️ Канонджи",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/10.jpg",
    },
    {
        "id": 11,
        "name": "⚡️ Зенносуке",
        "rarity": "Обычная",
        "attack": 1000,
        "health": 2000,
        "value": 1000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/11.jpg",
    },
    {
        "id": 12,
        "name": "✨ Садо Ясутора",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 5000,
        "value": 4500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/12.jpg",
    },
    {
        "id": 13,
        "name": "✨ Аарониро",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 6000,
        "value": 2400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/13.jpg",
    },
    {
        "id": 14,
        "name": "✨ Масаки Куросаки",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 5000,
        "value": 4500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/14.jpg",
    },
    {
        "id": 15,
        "name": "✨ Ячиру Кусаджиши",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 6000,
        "value": 4400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/15.jpg",
    },
    {
        "id": 16,
        "name": "✨ Лиза Ядомару",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 5000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/16.jpg",
    },
    {
        "id": 17,
        "name": "✨ Хисаги",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 5000,
        "value": 3400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/17.jpg",
    },
    {
        "id": 18,
        "name": "✨ Хиери",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 6000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/18.jpg",
    },
    {
        "id": 19,
        "name": "✨ Кайен Шиба",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 5000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/19.jpg",
    },
    {
        "id": 20,
        "name": "✨ Юширо Шихоин",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 5000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/20.jpg",
    },
    {
        "id": 21,
        "name": "✨ Рюукен",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 5000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/21.jpg",
    },
    {
        "id": 22,
        "name": "✨ Цукабиши",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 5000,
        "value": 2600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/22.jpg",
    },
    {
        "id": 23,
        "name": "✨ Иккаку",
        "rarity": "Редкая",
        "attack": 4000,
        "health": 6000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/23.jpg",
    },
    {
        "id": 24,
        "name": "✨ Орихиме Иноуз",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 5000,
        "value": 4400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/24.jpg",
    },
    {
        "id": 25,
        "name": "✨ Нему",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 6000,
        "value": 3600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/25.jpg",
    },
    {
        "id": 26,
        "name": "*✨ Тецузазмон Иба",
        "rarity": "Редкая",
        "attack": 3000,
        "health": 6000,
        "value": 2000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/26.jpg",
    },
    {
        "id": 27,
        "name": "🐉 Йоруичи",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 9000,
        "value": 9400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/27.jpg",
    },
    {
        "id": 28,
        "name": "🐉 Ямми Льярго",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 10000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/28.jpg",
    },
    {
        "id": 29,
        "name": "🐉 Хиконе Убугину",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 9000,
        "value": 7400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/29.jpg",
    },
    {
        "id": 30,
        "name": "🐉 Тия Харрибел",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 6000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/30.jpg",
    },
    {
        "id": 31,
        "name": "🐉 Рангику",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 6000,
        "value": 8400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/31.jpg",
    },
    {
        "id": 32,
        "name": "🐉 Заельапорро",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 6400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/32.jpg",
    },
    {
        "id": 33,
        "name": "🐉 Каторибацу",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 7000,
        "value": 6400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/33.jpg",
    },
    {
        "id": 34,
        "name": "🐉 Цукишима",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/34.jpg",
    },
    {
        "id": 35,
        "name": "🐉 Глупый Грэмми",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 10000,
        "value": 7400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/35.jpg",
    },
    {
        "id": 36,
        "name": "🐉 Ичимару Гин",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 9000,
        "value": 9400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/36.jpg",
    },
    {
        "id": 37,
        "name": "🐉 Синдзи",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 8600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/37.jpg",
    },
    {
        "id": 38,
        "name": "🐉 Нанао",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 7000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/38.jpg",
    },
    {
        "id": 39,
        "name": "🐉 Ренджи",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 9400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/39.jpg",
    },
    {
        "id": 40,
        "name": "🐉 Ишшин Куросаки",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 9500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/40.jpg",
    },
    {
        "id": 41,
        "name": "🐉 Нойтра Джилга",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 7000,
        "value": 6000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/41.jpg",
    },
    {
        "id": 42,
        "name": "🐉 Цанду",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 10000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/42.jpg",
    },
    {
        "id": 43,
        "name": "🐉 Юмичика",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/43.jpg",
    },
    {
        "id": 44,
        "name": "🐉 Фурофуши",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 7000,
        "value": 6600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/44.jpg",
    },
    {
        "id": 45,
        "name": "🐉 Кира",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 8600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/45.jpg",
    },
    {
        "id": 46,
        "name": "🐉 Люппи Антенор",
        "rarity": "Эпическая",
        "attack": 5000,
        "health": 7000,
        "value": 5400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/46.jpg",
    },
    {
        "id": 47,
        "name": "🐉 Бамбиетта",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 7400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/47.jpg",
    },
    {
        "id": 48,
        "name": "🐉 Пернида Парнкджас",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 10000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/48.jpg",
    },
    {
        "id": 49,
        "name": "🐉 Нелл",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 8400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/49.jpg",
    },
    {
        "id": 50,
        "name": "🐉 Исида",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 7000,
        "value": 9500,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/50.jpg",
    },
    {
        "id": 51,
        "name": "🐉 Токинада",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 8000,
        "value": 7400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/51.jpg",
    },
    {
        "id": 52,
        "name": "🐉 База-Би",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 8000,
        "value": 7400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/52.jpg",
    },
    {
        "id": 53,
        "name": "🐉 Старк",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 9000,
        "value": 7600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/53.jpg",
    },
    {
        "id": 54,
        "name": "🐉 Сой-Фон",
        "rarity": "Эпическая",
        "attack": 6000,
        "health": 7000,
        "value": 8400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/54.jpg",
    },
    {
        "id": 55,
        "name": "🐉 Азаширо Кенпачи",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 8000,
        "value": 6600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/55.jpg",
    },
    {
        "id": 56,
        "name": "🐉 Кучики Бьякуя",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 8000,
        "value": 9400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/56.jpg",
    },
    {
        "id": 57,
        "name": "🐉 Гримджоу",
        "rarity": "Эпическая",
        "attack": 7000,
        "health": 9000,
        "value": 8600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/57.jpg",
    },
    {
        "id": 58,
        "name": "🩸 Хицугая Тоширо",
        "rarity": "Легендарная",
        "attack": 8000,
        "health": 14000,
        "value": 12600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/58.jpg",
    },
    {
        "id": 59,
        "name": "🩸 Жерар",
        "rarity": "Легендарная",
        "attack": 10000,
        "health": 20000,
        "value": 12400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/59.jpg",
    },
    {
        "id": 60,
        "name": "🩸 Аскин Накк ле Вар",
        "rarity": "Легендарная",
        "attack": 9000,
        "health": 16000,
        "value": 11600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/60.jpg",
    },
    {
        "id": 61,
        "name": "🩸 Маюри Куроцучи",
        "rarity": "Легендарная",
        "attack": 8000,
        "health": 17000,
        "value": 13600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/61.jpg",
    },
    {
        "id": 62,
        "name": "🩸 Лилье Барро",
        "rarity": "Легендарная",
        "attack": 9000,
        "health": 15000,
        "value": 10400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/62.jpg",
    },
    {
        "id": 63,
        "name": "🩸 Барагган Луизенбарн",
        "rarity": "Легендарная",
        "attack": 9000,
        "health": 20000,
        "value": 10400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/63.jpg",
    },
    {
        "id": 64,
        "name": "🩸 Кискэ Урахара",
        "rarity": "Легендарная",
        "attack": 8000,
        "health": 14000,
        "value": 14600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/64.jpg",
    },
    {
        "id": 65,
        "name": "🩸 Хашвальт",
        "rarity": "Легендарная",
        "attack": 9000,
        "health": 16000,
        "value": 12400,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/65.jpg",
    },
    {
        "id": 66,
        "name": "🩸 Ройд Ллойд",
        "rarity": "Легендарная",
        "attack": 10000,
        "health": 20000,
        "value": 11600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/66.jpg",
    },
    {
        "id": 67,
        "name": "🩸 Кучики Рукия",
        "rarity": "Легендарная",
        "attack": 8000,
        "health": 16000,
        "value": 14000,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/67.jpg",
    },
    {
        "id": 68,
        "name": "🩸 Оэцу",
        "rarity": "Легендарная",
        "attack": 8000,
        "health": 14000,
        "value": 11600,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/68.jpg",
    },
    {
        "id": 69,
        "name": "🩸 Унохана",
        "rarity": "Легендарная",
        "attack": 000,
        "health": 000,
        "value": 00,
        "image_url": "https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/bleach/69.jpg",
    },
    {
        "id": 70,
        "name": "🧩 Урахара RE",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 000,
        "value": 00,
        "image_url": "mythic/bleach/70.gif",
    },
    {
        "id": 71,
        "name": "🧩 Молодой Яхве",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 18000,
        "value": 28000,
        "image_url": "mythic/bleach/71.gif",
    },
    {
        "id": 72,
        "name": "🧩 Рейо",
        "rarity": "Мифическая",
        "attack": 18000,
        "health": 22000,
        "value": 30000,
        "image_url": "mythic/bleach/72.gif",
    },
    {
        "id": 73,
        "name": "🧩 Кенпачи Зараки",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 21000,
        "value": 29600,
        "image_url": "mythic/bleach/73.gif",
    },
    {
        "id": 74,
        "name": "🧩 Йоруичи Пик",
        "rarity": "Мифическая",
        "attack": 16000,
        "health": 19000,
        "value": 27400,
        "image_url": "mythic/bleach/74.gif",
    },
    {
        "id": 75,
        "name": "🧩 Кьераку Шунсуй",
        "rarity": "Мифическая",
        "attack": 15000,
        "health": 19000,
        "value": 29400,
        "image_url": "mythic/bleach/75.gif",
    },
    {
        "id": 76,
        "name": "🧩 Ичибей",
        "rarity": "Мифическая",
        "attack": 16000,
        "health": 20000,
        "value": 29400,
        "image_url": "mythic/bleach/76.gif",
    },
    {
        "id": 77,
        "name": "🧩 Грэмми",
        "rarity": "Мифическая",
        "attack": 18000,
        "health": 22000,
        "value": 29000,
        "image_url": "mythic/bleach/77.gif",
    },
    {
        "id": 78,
        "name": "🧩 Яхве",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 22000,
        "value": 30000,
        "image_url": "mythic/bleach/78.gif",
    },
    {
        "id": 79,
        "name": "🧩 Тошира RE",
        "rarity": "Мифическая",
        "attack": 15000,
        "health": 17000,
        "value": 27300,
        "image_url": "mythic/bleach/79.gif",
    },
    {
        "id": 80,
        "name": "🧩 Ичиго Куросаки",
        "rarity": "Мифическая",
        "attack": 15000,
        "health": 20000,
        "value": 30000,
        "image_url": "mythic/bleach/80.gif",
    },
    {
        "id": 81,
        "name": "🧩 Ичиго Мугецу",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 21000,
        "value": 30000,
        "image_url": "mythic/bleach/81.gif",
    },
    {
        "id": 82,
        "name": "🧩 Васто Лорде",
        "rarity": "Мифическая",
        "attack": 18000,
        "health": 21000,
        "value": 29000,
        "image_url": "mythic/bleach/82.gif",
    },
    {
        "id": 83,
        "name": "🧩 Господин Айзен",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 22000,
        "value": 29600,
        "image_url": "mythic/bleach/83.gif",
    },
    {
        "id": 84,
        "name": "🧩 Ямамото Генрюсай",
        "rarity": "Мифическая",
        "attack": 15000,
        "health": 19000,
        "value": 29600,
        "image_url": "mythic/bleach/84.gif",
    },
    {
        "id": 85,
        "name": "🧩 Улькиорра Шифер",
        "rarity": "Мифическая",
        "attack": 15000,
        "health": 18000,
        "value": 27600,
        "image_url": "mythic/bleach/85.gif",
    },
    {
        "id": 86,
        "name": "🧩 Куго Гинджоу",
        "rarity": "Мифическая",
        "attack": 16000,
        "health": 18000,
        "value": 26600,
        "image_url": "mythic/bleach/86.gif",
    },
    {
        "id": 87,
        "name": "🧩 Господин Кон",
        "rarity": "Мифическая",
        "attack": 16000,
        "health": 22000,
        "value": 23600,
        "image_url": "mythic/bleach/87.gif",
    },
    {
        "id": 88,
        "name": "🧩 Ичиго ФВ",
        "rarity": "Мифическая",
        "attack": 17000,
        "health": 20000,
        "value": 28500,
        "image_url": "mythic/bleach/88.gif",
    },
    {
        "id": 89,
        "name": "🧩 Юграм Хашвальт",
        "rarity": "Мифическая",
        "attack": 17500,
        "health": 21500,
        "value": 29000,
        "image_url": "mythic/bleach/89.gif",
    }
]