parsed_data = [
    {
        'id': 1,
        'name': '⚡️ Регистил',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/1.jpg',
    },
    {
        'id': 2,
        'name': '⚡️ Голдак',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/2.jpg',
    },
    {
        'id': 3,
        'name': '⚡️ Додрио',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/3.jpg',
    },
    {
        'id': 4,
        'name': '⚡️ Флоутзел',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/4.jpg',
    },
    {
        'id': 5,
        'name': '⚡️ Скантанк',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/5.jpg',
    },
    {
        'id': 6,
        'name': '⚡️ Сколипед',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/6.jpg',
    },
    {
        'id': 7,
        'name': '⚡️ Бруксиш',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/7.jpg',
    },
    {
        'id': 8,
        'name': '⚡️ Гарбодор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/8.jpg',
    },
    {
        'id': 9,
        'name': '⚡️ Мистер Майм',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/9.jpg',
    },
    {
        'id': 10,
        'name': '⚡️ Зангус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/10.jpg',
    },
    {
        'id': 11,
        'name': '⚡️ Скрафти',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/11.jpg',
    },
    {
        'id': 12,
        'name': '⚡️ Маскерейн',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/12.jpg',
    },
    {
        'id': 13,
        'name': '⚡️ Лурантис',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/13.jpg',
    },
    {
        'id': 14,
        'name': '⚡️ Милтанк',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/14.jpg',
    },
    {
        'id': 15,
        'name': '⚡️ Коалоссал',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/15.jpg',
    },
    {
        'id': 16,
        'name': '⚡️ Меганиум',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/16.jpg',
    },
    {
        'id': 17,
        'name': '⚡️ Орикорио',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/17.jpg',
    },
    {
        'id': 18,
        'name': '⚡️ Стиликс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/18.jpg',
    },
    {
        'id': 19,
        'name': '⚡️ Уэйлорд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/19.jpg',
    },
    {
        'id': 20,
        'name': '⚡️ Магмар',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/20.jpg',
    },
    {
        'id': 21,
        'name': '⚡️ Дабвул',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/21.jpg',
    },
    {
        'id': 22,
        'name': '⚡️ Солрок',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/22.jpg',
    },
    {
        'id': 23,
        'name': '⚡️ Туртонатор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/23.jpg',
    },
    {
        'id': 24,
        'name': '⚡️ Гридент',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/24.jpg',
    },
    {
        'id': 25,
        'name': '⚡️ Персеркер',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/25.jpg',
    },
    {
        'id': 26,
        'name': '⚡️ Виктрибел',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/26.jpg',
    },
    {
        'id': 27,
        'name': '⚡️ Найтэйлс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/27.jpg',
    },
    {
        'id': 28,
        'name': '⚡️ Симисейдж',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/28.jpg',
    },
    {
        'id': 29,
        'name': '⚡️ Драпион',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/29.jpg',
    },
    {
        'id': 30,
        'name': '⚡️ Беллоссом',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/30.jpg',
    },
    {
        'id': 31,
        'name': '⚡️ Октилери',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/31.jpg',
    },
    {
        'id': 32,
        'name': '⚡️ Уизинг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/32.jpg',
    },
    {
        'id': 33,
        'name': '⚡️ Хитмор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/33.jpg',
    },
    {
        'id': 34,
        'name': '⚡️ Амбипом',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/34.jpg',
    },
    {
        'id': 35,
        'name': '⚡️ Гастродон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/35.jpg',
    },
    {
        'id': 36,
        'name': '⚡️ Крадили',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/36.jpg',
    },
    {
        'id': 37,
        'name': '⚡️ Марактус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/37.jpg',
    },
    {
        'id': 38,
        'name': '⚡️ Лудиколо',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/38.jpg',
    },
    {
        'id': 39,
        'name': '⚡️ Акселгор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/39.jpg',
    },
    {
        'id': 40,
        'name': '⚡️ Фалинкс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/40.jpg',
    },
    {
        'id': 41,
        'name': '⚡️ Сосбак',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/41.jpg',
    },
    {
        'id': 42,
        'name': '⚡️ Политоуд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/42.jpg',
    },
    {
        'id': 43,
        'name': '⚡️ Бронзонг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/43.jpg',
    },
    {
        'id': 44,
        'name': '⚡️ Абомасноу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/44.jpg',
    },
    {
        'id': 45,
        'name': '⚡️ Банетт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/45.jpg',
    },
    {
        'id': 46,
        'name': '⚡️ Кофагригус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/46.jpg',
    },
    {
        'id': 47,
        'name': '⚡️ Готител',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/47.jpg',
    },
    {
        'id': 48,
        'name': '⚡️ Кактурна',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/48.jpg',
    },
    {
        'id': 49,
        'name': '⚡️ Пилосвайн',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/49.jpg',
    },
    {
        'id': 50,
        'name': '⚡️ Лунатон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/50.jpg',
    },
    {
        'id': 51,
        'name': '⚡️ Пикачу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/51.jpg',
    },
    {
        'id': 52,
        'name': '⚡️ Чинчино',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/52.jpg',
    },
    {
        'id': 53,
        'name': '⚡️ Грумпиг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/53.jpg',
    },
    {
        'id': 54,
        'name': '⚡️ Шифтри',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/54.jpg',
    },
    {
        'id': 55,
        'name': '⚡️ Зату',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/55.jpg',
    },
    {
        'id': 56,
        'name': '⚡️ Даскнуар',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/56.jpg',
    },
    {
        'id': 57,
        'name': '⚡️ Сэндслаш',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/57.jpg',
    },
    {
        'id': 58,
        'name': '⚡️ Примейп',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/58.jpg',
    },
    {
        'id': 59,
        'name': '⚡️ Электабаза',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/59.jpg',
    },
    {
        'id': 60,
        'name': '⚡️ Орангуру',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/60.jpg',
    },
    {
        'id': 61,
        'name': '⚡️ Фрэкшур',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/61.jpg',
    },
    {
        'id': 62,
        'name': '⚡️ Райчу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/62.jpg',
    },
    {
        'id': 63,
        'name': '⚡️ Чимеко',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/63.jpg',
    },
    {
        'id': 64,
        'name': '⚡️ Манектрик',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/64.jpg',
    },
    {
        'id': 65,
        'name': '⚡️ Тангела',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/65.jpg',
    },
    {
        'id': 66,
        'name': '⚡️ Орбитэл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/66.jpg',
    },
    {
        'id': 67,
        'name': '⚡️ Эпплтан',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/67.jpg',
    },
    {
        'id': 68,
        'name': '⚡️ Зебстрика',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/68.jpg',
    },
    {
        'id': 69,
        'name': '⚡️ Палоссанд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/69.jpg',
    },
    {
        'id': 70,
        'name': '⚡️ Галвантула',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/70.jpg',
    },
    {
        'id': 71,
        'name': '⚡️ Дрифблим',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/71.jpg',
    },
    {
        'id': 72,
        'name': '⚡️ Симисир',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/72.jpg',
    },
    {
        'id': 73,
        'name': '⚡️ Индиди',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/73.jpg',
    },
    {
        'id': 74,
        'name': '⚡️ Форретрес',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/74.jpg',
    },
    {
        'id': 75,
        'name': '⚡️ Серпериор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/75.jpg',
    },
    {
        'id': 76,
        'name': '⚡️ Ферроторн',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/76.jpg',
    },
    {
        'id': 77,
        'name': '⚡️ Псайдак',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/77.jpg',
    },
    {
        'id': 78,
        'name': '⚡️ Арктовиш',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/78.jpg',
    },
    {
        'id': 79,
        'name': '⚡️ Хитмончан',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/79.jpg',
    },
    {
        'id': 80,
        'name': '⚡️ Джеллисент',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/80.jpg',
    },
    {
        'id': 81,
        'name': '⚡️ Камерапт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/81.jpg',
    },
    {
        'id': 82,
        'name': '⚡️ Калайрекс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/82.jpg',
    },
    {
        'id': 83,
        'name': '⚡️ Рибомби',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/83.jpg',
    },
    {
        'id': 84,
        'name': '⚡️ Эксплауд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/84.jpg',
    },
    {
        'id': 85,
        'name': '⚡️ Гамшус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/85.jpg',
    },
    {
        'id': 86,
        'name': '⚡️ Симипур',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/86.jpg',
    },
    {
        'id': 87,
        'name': '⚡️ Мимикью',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/87.jpg',
    },
    {
        'id': 88,
        'name': '⚡️ Тентакрул',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/88.jpg',
    },
    {
        'id': 89,
        'name': '⚡️ Клефейбл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/89.jpg',
    },
    {
        'id': 90,
        'name': '✨ Поливрат',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/90.jpg',
    },
    {
        'id': 91,
        'name': '✨ Слоукинг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/91.jpg',
    },
    {
        'id': 92,
        'name': '✨ Обстагун',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/92.jpg',
    },
    {
        'id': 93,
        'name': '✨ Арктозолт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/93.jpg',
    },
    {
        'id': 94,
        'name': '✨ Флаппл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/94.jpg',
    },
    {
        'id': 95,
        'name': '✨ Старми',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/95.jpg',
    },
    {
        'id': 96,
        'name': '✨ Барраскьюда',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/96.jpg',
    },
    {
        'id': 97,
        'name': '✨ Абсол',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/97.jpg',
    },
    {
        'id': 98,
        'name': '✨ Джинкс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/98.jpg',
    },
    {
        'id': 99,
        'name': '✨ Салазал',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/99.jpg',
    },
    {
        'id': 100,
        'name': '✨ Электрос',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/100.jpg',
    },
    {
        'id': 101,
        'name': '✨ Алкреми',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/101.jpg',
    },
    {
        'id': 102,
        'name': '✨ Гранбулл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/102.jpg',
    },
    {
        'id': 103,
        'name': '✨ ПНоригон 2',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/103.jpg',
    },
    {
        'id': 104,
        'name': '✨ Кангаскан',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/104.jpg',
    },
    {
        'id': 105,
        'name': '✨ Зороарк',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/105.jpg',
    },
    {
        'id': 106,
        'name': '✨ Уолрейн',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/106.jpg',
    },
    {
        'id': 107,
        'name': '✨ Фросмот',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/107.jpg',
    },
    {
        'id': 108,
        'name': '✨ Флайгон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/108.jpg',
    },
    {
        'id': 109,
        'name': '✨ Лукарио',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/109.jpg',
    },
    {
        'id': 110,
        'name': '✨ Клойстер',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/110.jpg',
    },
    {
        'id': 111,
        'name': '✨ Кингдра',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/111.jpg',
    },
    {
        'id': 112,
        'name': '✨ Драддигон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/112.jpg',
    },
    {
        'id': 113,
        'name': '✨ Тауррос',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/113.jpg',
    },
    {
        'id': 114,
        'name': '✨ Брилум',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/114.jpg',
    },
    {
        'id': 115,
        'name': '✨ Мушарна',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/115.jpg',
    },
    {
        'id': 116,
        'name': '14 Нидокинг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/116.jpg',
    },
    {
        'id': 117,
        'name': '✨ Лиллигант',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/117.jpg',
    },
    {
        'id': 118,
        'name': '✨Е Арктовиш',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/118.jpg',
    },
    {
        'id': 119,
        'name': '✨ Хонкроу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/119.jpg',
    },
    {
        'id': 120,
        'name': '✨ Туканнон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/120.jpg',
    },
    {
        'id': 121,
        'name': '*} Слоубро',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/121.jpg',
    },
    {
        'id': 122,
        'name': '✨ Лапрас',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/122.jpg',
    },
    {
        'id': 123,
        'name': '✨ Унфезант',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/123.jpg',
    },
    {
        'id': 124,
        'name': '14ф Хитмонли',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/124.jpg',
    },
    {
        'id': 125,
        'name': '✨ Карракоста',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/125.jpg',
    },
    {
        'id': 126,
        'name': '✨Токстрицити',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/126.jpg',
    },
    {
        'id': 127,
        'name': '✨ Крастл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/127.jpg',
    },
    {
        'id': 128,
        'name': '✨ Бластойз',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/128.jpg',
    },
    {
        'id': 129,
        'name': '✨ Реликант',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/129.jpg',
    },
    {
        'id': 130,
        'name': '✨ Корвикнайт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/130.jpg',
    },
    {
        'id': 131,
        'name': '`'✨  Дурант',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/131.jpg',
    },
    {
        'id': 132,
        'name': '✨ Тайт: Налл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/132.jpg',
    },
    {
        'id': 133,
        'name': '✨ Магнетон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/133.jpg',
    },
    {
        'id': 134,
        'name': '✨ Хаундум',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/134.jpg',
    },
    {
        'id': 135,
        'name': '✨ Кробат',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/135.jpg',
    },
    {
        'id': 136,
        'name': '14 Мизмагиус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/136.jpg',
    },
    {
        'id': 137,
        'name': '✨ Лайканрок',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/137.jpg',
    },
    {
        'id': 138,
        'name': '✨ Ликилики',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/138.jpg',
    },
    {
        'id': 139,
        'name': '✨ Венозавр',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/139.jpg',
    },
    {
        'id': 140,
        'name': '✨ Ливанни',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/140.jpg',
    },
    {
        'id': 141,
        'name': '✨ Троу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/141.jpg',
    },
    {
        'id': 142,
        'name': '✨ Комала',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/142.jpg',
    },
    {
        'id': 143,
        'name': '✨ Миеншао',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/143.jpg',
    },
    {
        'id': 144,
        'name': '✨ Рапидаш',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/144.jpg',
    },
    {
        'id': 145,
        'name': '✨ Кроудонт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/145.jpg',
    },
    {
        'id': 146,
        'name': '✨ Сайсмитоуд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/146.jpg',
    },
    {
        'id': 147,
        'name': '✨ Инфернейп',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/147.jpg',
    },
    {
        'id': 148,
        'name': '✨  Плискор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/148.jpg',
    },
    {
        'id': 149,
        'name': '✨ Вайлплюм',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/149.jpg',
    },
    {
        'id': 150,
        'name': '✨ Сигилиф',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/150.jpg',
    },
    {
        'id': 151,
        'name': '✨ Клинкланг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/151.jpg',
    },
    {
        'id': 152,
        'name': '✨ Грапплокт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/152.jpg',
    },
    {
        'id': 153,
        'name': '5) Омастар',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/153.jpg',
    },
    {
        'id': 154,
        'name': '5) Феромоза',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/154.jpg',
    },
    {
        'id': 155,
        'name': '„5) Крабоминабл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/155.jpg',
    },
    {
        'id': 156,
        'name': '&) Ванилюкс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/156.jpg',
    },
    {
        'id': 157,
        'name': '5) Мак',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/157.jpg',
    },
    {
        'id': 158,
        'name': '5) Пинсир',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/158.jpg',
    },
    {
        'id': 159,
        'name': '„&) Лаксрей',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/159.jpg',
    },
    {
        'id': 160,
        'name': '„&) Селтайл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/160.jpg',
    },
    {
        'id': 161,
        'name': '&) Креселия',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/161.jpg',
    },
    {
        'id': 162,
        'name': '25) Голурк',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/162.jpg',
    },
    {
        'id': 163,
        'name': '„&) Эскавальер',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/163.jpg',
    },
    {
        'id': 164,
        'name': '5) Джолтеон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/164.jpg',
    },
    {
        'id': 165,
        'name': '&) Самуротт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/165.jpg',
    },
    {
        'id': 166,
        'name': '5) Дрампа',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/166.jpg',
    },
    {
        'id': 167,
        'name': '„&) Газалорд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/167.jpg',
    },
    {
        'id': 168,
        'name': '&) Тапу Фини',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/168.jpg',
    },
    {
        'id': 169,
        'name': '„5) Реджиэлеки',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/169.jpg',
    },
    {
        'id': 170,
        'name': '„5) Тайфлозион',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/170.jpg',
    },
    {
        'id': 171,
        'name': '5) Голем',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/171.jpg',
    },
    {
        'id': 172,
        'name': '„5) Стаутланд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/172.jpg',
    },
    {
        'id': 173,
        'name': '&) Соук',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/173.jpg',
    },
    {
        'id': 174,
        'name': '„5) Эмполеон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/174.jpg',
    },
    {
        'id': 175,
        'name': '5) Силвалли',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/175.jpg',
    },
    {
        'id': 176,
        'name': '5) Фералигейтор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/176.jpg',
    },
    {
        'id': 177,
        'name': '5) Бишарт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/177.jpg',
    },
    {
        'id': 178,
        'name': '&) Урсаринг',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/178.jpg',
    },
    {
        'id': 179,
        'name': '„5) Чаризард',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/179.jpg',
    },
    {
        'id': 180,
        'name': '5) Янмега',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/180.jpg',
    },
    {
        'id': 181,
        'name': '&) Кинглер',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/181.jpg',
    },
    {
        'id': 182,
        'name': '„5) Дианси',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/182.jpg',
    },
    {
        'id': 183,
        'name': '5) Буффалант',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/183.jpg',
    },
    {
        'id': 184,
        'name': '5) Реюниклус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/184.jpg',
    },
    {
        'id': 185,
        'name': '5) Десиджуай',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/185.jpg',
    },
    {
        'id': 186,
        'name': '5) Лифион',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/186.jpg',
    },
    {
        'id': 187,
        'name': '5) Генгар',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/187.jpg',
    },
    {
        'id': 188,
        'name': '5) Блейзикен',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/188.jpg',
    },
    {
        'id': 189,
        'name': '5) Царина',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/189.jpg',
    },
    {
        'id': 190,
        'name': '25) Тортерра',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/190.jpg',
    },
    {
        'id': 191,
        'name': '&) Хаттерен',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/191.jpg',
    },
    {
        'id': 192,
        'name': '„&) Сандаконда',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/192.jpg',
    },
    {
        'id': 193,
        'name': '„5) Криогонал',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/193.jpg',
    },
    {
        'id': 194,
        'name': '5) Армальдо',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/194.jpg',
    },
    {
        'id': 195,
        'name': '5) Дреднав',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/195.jpg',
    },
    {
        'id': 196,
        'name': '5) Блисси',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/196.jpg',
    },
    {
        'id': 197,
        'name': '„5) Гримснарл',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/197.jpg',
    },
    {
        'id': 198,
        'name': '„5) Стэраптор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/198.jpg',
    },
    {
        'id': 199,
        'name': '„5) Бихийем',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/199.jpg',
    },
    {
        'id': 200,
        'name': '5) Харияма',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/200.jpg',
    },
    {
        'id': 201,
        'name': '„5) Интелеон',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/201.jpg',
    },
    {
        'id': 202,
        'name': '„5) Оверквил',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/202.jpg',
    },
    {
        'id': 203,
        'name': '&) Амфарос',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/203.jpg',
    },
    {
        'id': 204,
        'name': '5) Делмайз',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/204.jpg',
    },
    {
        'id': 205,
        'name': '& Слектрир',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/205.jpg',
    },
    {
        'id': 206,
        'name': '@ Баззвол',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/206.jpg',
    },
    {
        'id': 207,
        'name': '& Драгонайт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/207.jpg',
    },
    {
        'id': 208,
        'name': '& Магирна',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/208.jpg',
    },
    {
        'id': 209,
        'name': '& Лугия',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/209.jpg',
    },
    {
        'id': 210,
        'name': '& Мелметал',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/210.jpg',
    },
    {
        'id': 211,
        'name': '& Картана',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/211.jpg',
    },
    {
        'id': 212,
        'name': '& Саламенс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/212.jpg',
    },
    {
        'id': 213,
        'name': '& Вольканион',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/213.jpg',
    },
    {
        'id': 214,
        'name': '& Голденго',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/214.jpg',
    },
    {
        'id': 215,
        'name': '@в Заруд',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/215.jpg',
    },
    {
        'id': 216,
        'name': '& Келдео',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/216.jpg',
    },
    {
        'id': 217,
        'name': '& Латиас',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/217.jpg',
    },
    {
        'id': 218,
        'name': '& Кайрем',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/218.jpg',
    },
    {
        'id': 219,
        'name': '& Ландорус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/219.jpg',
    },
    {
        'id': 220,
        'name': 'в Райпериор',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/220.jpg',
    },
    {
        'id': 221,
        'name': '& Замазента',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/221.jpg',
    },
    {
        'id': 222,
        'name': '& Метагросс',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/222.jpg',
    },
    {
        'id': 223,
        'name': '& Драгапульт',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/223.jpg',
    },
    {
        'id': 224,
        'name': '& Терракион',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/224.jpg',
    },
    {
        'id': 225,
        'name': '& Уринфу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/225.jpg',
    },
    {
        'id': 226,
        'name': '& Некрозма',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/226.jpg',
    },
    {
        'id': 227,
        'name': '& Хаксорус',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/227.jpg',
    },
    {
        'id': 228,
        'name': '& Запдос',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/228.jpg',
    },
    {
        'id': 229,
        'name': '& Волькарона',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/229.jpg',
    },
    {
        'id': 230,
        'name': '& ТалуЛеле',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/230.jpg',
    },
    {
        'id': 231,
        'name': '& Молтрес',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/231.jpg',
    },
    {
        'id': 232,
        'name': '& Зераора',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/232.jpg',
    },
    {
        'id': 233,
        'name': '& Райку',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/233.jpg',
    },
    {
        'id': 234,
        'name': '@ Талу Булу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/234.jpg',
    },
    {
        'id': 235,
        'name': '& Энтей',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/235.jpg',
    },
    {
        'id': 236,
        'name': '& Латиос',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/236.jpg',
    },
    {
        'id': 237,
        'name': 'в Маршадоу',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/237.jpg',
    },
    {
        'id': 238,
        'name': '& Зациан',
        'rarity': '',
        'attack': ,
        'health': ,
        'value': ,
        'image_url': 'https://raw.githubusercontent.com/prister884/aniverse-files/refs/heads/main/pokemon/238.jpg',
    },
]
